INFO - 2024-01-30 14:05:31,098 в строке 80" : Программой получены аргументы Namespace(numbers=['23.11.1971'])
INFO - 2024-01-30 14:05:31,099 в строке 34" : Выполнена функция: check_date() аргументы функции: ('23.11.1971',), результат функции: True
INFO - 2024-01-30 14:05:31,099 в строке 34" : Выполнена функция: check_date() аргументы функции: ('12.13.9999',), результат функции: False
INFO - 2024-01-30 14:05:31,099 в строке 34" : Выполнена функция: check_date() аргументы функции: ('01.02.2024',), результат функции: True
ERROR - 2024-01-30 14:05:31,099 в строке 31" : Ошибка ValueError в функции: check_date() - введен некорректный аргумент ('sdsds',)
